version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: marcello
      POSTGRES_PASSWORD: marcello123
      POSTGRES_DB: animes
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=marcello
      - RABBITMQ_DEFAULT_PASS=123

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  db-data:
  rabbitmq_data:
  redis_data: